# Generated by Django 6.1.1 on 2026-09-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='IATA airport code, e.g. DEL', max_length=10, unique=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('airport_name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('country_code', models.CharField(blank=True, default='IN', max_length=2)),
                ('is_popular', models.BooleanField(default=False, help_text='Shown first in the default/empty-query autocomplete list.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive airports are hidden from search without deleting them.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city', 'code'],
                'indexes': [models.Index(fields=['is_active', 'is_popular'], name='flight_airp_is_acti_7391ab_idx')],
            },
        ),
    ]
