# Generated by Django 6.1.1 on 2026-09-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_seed_airports'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='airport',
            new_name='Airport_is_acti_4161af_idx',
            old_name='flight_airp_is_acti_7391ab_idx',
        ),
        migrations.AlterModelTable(
            name='airport',
            table='Airport',
        ),
    ]
