# Generated by Django 6.1.1 on 2026-09-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_rename_flight_airp_is_acti_7391ab_idx_airport_is_acti_4161af_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='airport',
            new_name='Airport_IS_ACTI_7f9286_idx',
            old_name='Airport_is_acti_4161af_idx',
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_name',
            field=models.CharField(db_column='AIRPORT_NAME', max_length=255),
        ),
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(db_column='CITY', db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(db_column='IATA_CODE', db_index=True, help_text='3-letter IATA airport code, e.g. DEL', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(blank=True, db_column='COUNTRY', default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country_code',
            field=models.CharField(blank=True, db_column='COUNTRY_CODE', default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='airport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CREATED_AT'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='is_active',
            field=models.BooleanField(db_column='IS_ACTIVE', default=True, help_text='Inactive airports are hidden from search without deleting them.'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='is_popular',
            field=models.BooleanField(db_column='IS_POPULAR', default=False, help_text='Shown first in the default/empty-query autocomplete list.'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UPDATED_AT'),
        ),
    ]
