"""
Django settings for MAIN project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dev-only-change-this-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
    'booking',
    'UserInterface',
    'interactions',
    'flight',
    'hotel',
    'wishlist',
    'support',
    'accounts',
    'legal',
    'religious',
    'aviation'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MAIN.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MAIN.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Defaults to SQLite so anyone can clone this project and run it
# straight away with no extra setup. If you want SQL Server (like the
# original local dev machine was using), set DB_ENGINE=mssql and the
# other DB_* variables in your own .env - nothing here is hardcoded to
# one person's machine anymore.

# DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite3')

# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',
#         'NAME': 'Booking_Test',
#         # 'HOST': 'DELL\SQLEXPRESS',
#         'HOST': r'DELL\SQLEXPRESS',
#         'PORT': '',
#         'OPTIONS': {
#             'driver': 'ODBC Driver 17 for SQL Server',
#             'trusted_connection': 'yes',
#         },
#     },
# }

# Database configuration
DB_ENGINE = os.environ.get("DB_ENGINE", "sqlite3").strip().lower()

if DB_ENGINE == "mssql":
    DATABASES = {
        "default": {
            "ENGINE": "mssql",
            "NAME": os.environ.get("DB_NAME", ""),
            "USER": os.environ.get("DB_USER", ""),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", ""),
            "PORT": os.environ.get("DB_PORT", "1433"),
            "OPTIONS": {
                "driver": os.environ.get(
                    "DB_DRIVER",
                    "ODBC Driver 17 for SQL Server",
                ),
                "Encrypt": os.environ.get("DB_ENCRYPT", "no"),
                "TrustServerCertificate": os.environ.get(
                    "DB_TRUST_SERVER_CERTIFICATE",
                    "yes",
                ),
            },
        },
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        },
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "assets",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email
# Django 6.1 uses the MAILERS configuration.
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# TripJack (flight supplier) configuration.
# Used by the TripJack flight search/review/seat-map integration.
# Switching environments remains a configuration change only.
# Values are read from environment variables / .env and must never be
# hardcoded or committed.
TRIPJACK_API_KEY = os.environ.get('TRIPJACK_API_KEY', '')
TRIPJACK_BASE_URL = os.environ.get('TRIPJACK_BASE_URL', '')
TRIPJACK_ENV = os.environ.get('TRIPJACK_ENV', 'test')
TRIPJACK_TIMEOUT_SECONDS = int(os.environ.get('TRIPJACK_TIMEOUT_SECONDS', '22'))
TRIPJACK_INCLUDE_DIRECT_FLIGHTS = os.environ.get('TRIPJACK_INCLUDE_DIRECT_FLIGHTS', 'True') == 'True'
TRIPJACK_INCLUDE_CONNECTING_FLIGHTS = os.environ.get('TRIPJACK_INCLUDE_CONNECTING_FLIGHTS', 'True') == 'True'

# Active flight supplier. Only 'tripjack' is a recognized real
# provider (see flight/providers/manager.py). Any other value -
# including the default 'unconfigured' - safely resolves to
# UnconfiguredProvider, which never returns flight data. There is no
# valid configuration value that selects the mock provider; it can
# only be used directly by automated tests.
FLIGHT_PROVIDER = os.environ.get('FLIGHT_PROVIDER', 'unconfigured')

# TripJack Hotel API v3 (same TripJack account/API key as flight;
# hotels use a separate pair of base URLs - see hotel/providers/tripjack_client.py).
HOTEL_HMS_BASE_URL = os.environ.get('HOTEL_HMS_BASE_URL', 'https://apitest-hms.tripjack.com')
# NOTE: the API reference documents a separate
# apitest-hotel-booker.tripjack.com host for Book/Booking-Details, but
# that host returns 403 "Access denied: IP address not whitelisted" -
# it needs IP whitelisting this environment doesn't have. Verified
# live that the same oms/v3/hotel/book and oms/v3/hotel/booking-details
# paths work correctly under the main apitest.tripjack.com host
# instead, with no whitelisting required.
HOTEL_BOOKER_BASE_URL = os.environ.get('HOTEL_BOOKER_BASE_URL', 'https://apitest.tripjack.com')

# Active hotel supplier. Only 'tripjack' is a recognized real provider
# (see hotel/providers/manager.py). Any other value - including the
# default 'unconfigured' - safely resolves to UnconfiguredHotelProvider,
# which never returns hotel data.
HOTEL_PROVIDER = os.environ.get('HOTEL_PROVIDER', 'unconfigured')

# Shared application settings. Keep environment-specific values outside source code.
DEFAULT_CURRENCY = os.environ.get('DEFAULT_CURRENCY', 'INR')
FRONTEND_PAGE_SIZE = int(os.environ.get('FRONTEND_PAGE_SIZE', '20'))

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}
