# Generated by Django 6.1.1 on 2026-09-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aircraft',
            name='Aircraft_categor_d6e0fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='aircraft',
            name='Aircraft_aircraf_437acb_idx',
        ),
        migrations.RemoveIndex(
            model_name='aircraft',
            name='Aircraft_is_feat_888fa3_idx',
        ),
        migrations.RemoveField(
            model_name='aircraftfeature',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='aircraftservice',
            name='aircraft',
        ),
        migrations.RemoveIndex(
            model_name='aircraftimage',
            name='AircraftIma_aircraf_b31337_idx',
        ),
        migrations.RemoveIndex(
            model_name='aircraftimage',
            name='AircraftIma_aircraf_f67d89_idx',
        ),
        migrations.RemoveIndex(
            model_name='aircraftspecification',
            name='AircraftSpe_aircraf_be1a9a_idx',
        ),
        migrations.RemoveIndex(
            model_name='aircraftspecification',
            name='AircraftSpe_aircraf_1260b0_idx',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='category',
        ),
        migrations.DeleteModel(
            name='AircraftFeature',
        ),
        migrations.DeleteModel(
            name='AircraftService',
        ),
        migrations.RemoveField(
            model_name='aircraftimage',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='aircraftspecification',
            name='aircraft',
        ),
        migrations.DeleteModel(
            name='AircraftCategory',
        ),
        migrations.DeleteModel(
            name='AircraftImage',
        ),
        migrations.DeleteModel(
            name='Aircraft',
        ),
        migrations.DeleteModel(
            name='AircraftSpecification',
        ),
    ]
