# Generated by Django 6.1.1 on 2026-09-12 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aviation', '0004_remove_aircraft_aircraft_categor_d6e0fb_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='Category image URL.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aircraft Category',
                'verbose_name_plural': 'Aircraft Categories',
                'db_table': 'AircraftCategory',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(choices=[('HELICOPTER', 'Helicopter'), ('PRIVATE_JET', 'Private Jet'), ('BUSINESS_JET', 'Business Jet'), ('COMMERCIAL', 'Commercial Aircraft'), ('TURBOPROP', 'Turboprop'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('primary_image_url', models.URLField(blank=True, help_text='Main image displayed on aircraft cards.')),
                ('passenger_capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of passengers.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('cruising_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('speed_unit', models.CharField(choices=[('knots', 'Knots'), ('km/h', 'Kilometers per hour'), ('mph', 'Miles per hour')], default='knots', max_length=20)),
                ('luggage_capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('luggage_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds'), ('liters', 'Liters')], default='kg', max_length=20)),
                ('pilot_count', models.PositiveIntegerField(default=1)),
                ('flight_attendant_count', models.PositiveIntegerField(default=0)),
                ('has_flight_attendant', models.BooleanField(default=False)),
                ('range_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('range_unit', models.CharField(choices=[('km', 'Kilometers'), ('miles', 'Miles'), ('nm', 'Nautical miles')], default='km', max_length=20)),
                ('lavatory_count', models.PositiveIntegerField(default=0)),
                ('wifi_available', models.BooleanField(default=False)),
                ('cabin_description', models.TextField(blank=True)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_currency', models.CharField(default='INR', max_length=3)),
                ('price_unit', models.CharField(choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('trip', 'Per Trip'), ('flight', 'Per Flight'), ('request', 'On Request')], default='request', max_length=20)),
                ('is_price_on_request', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='aviation.aircraftcategory')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
                'db_table': 'Aircraft',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AircraftFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name or CSS class.', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='aviation.aircraft')),
            ],
            options={
                'verbose_name': 'Aircraft Feature',
                'verbose_name_plural': 'Aircraft Features',
                'db_table': 'AircraftFeature',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AircraftImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('HERO', 'Hero Image'), ('EXTERIOR', 'Exterior'), ('INTERIOR', 'Interior'), ('CABIN', 'Cabin'), ('COCKPIT', 'Cockpit'), ('SEAT_MAP', 'Seat Map'), ('GALLERY', 'Gallery'), ('OTHER', 'Other')], default='GALLERY', max_length=20)),
                ('image_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=150)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aviation.aircraft')),
            ],
            options={
                'verbose_name': 'Aircraft Image',
                'verbose_name_plural': 'Aircraft Images',
                'db_table': 'AircraftImage',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AircraftService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('price_unit', models.CharField(blank=True, max_length=50)),
                ('is_price_on_request', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='aviation.aircraft')),
            ],
            options={
                'verbose_name': 'Aircraft Service',
                'verbose_name_plural': 'Aircraft Services',
                'db_table': 'AircraftService',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AircraftSpecification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(default='Technical Specifications', max_length=100)),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='aviation.aircraft')),
            ],
            options={
                'verbose_name': 'Aircraft Specification',
                'verbose_name_plural': 'Aircraft Specifications',
                'db_table': 'AircraftSpecification',
                'ordering': ['section_name', 'group_name', 'display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['category', 'is_active'], name='Aircraft_categor_d6e0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['aircraft_type', 'is_active'], name='Aircraft_aircraf_437acb_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['is_featured', 'is_active'], name='Aircraft_is_feat_888fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraftimage',
            index=models.Index(fields=['aircraft', 'image_type'], name='AircraftIma_aircraf_b31337_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraftimage',
            index=models.Index(fields=['aircraft', 'is_active'], name='AircraftIma_aircraf_f67d89_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraftspecification',
            index=models.Index(fields=['aircraft', 'section_name'], name='AircraftSpe_aircraf_be1a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='aircraftspecification',
            index=models.Index(fields=['aircraft', 'is_active'], name='AircraftSpe_aircraf_1260b0_idx'),
        ),
    ]
