# Generated by Django 6.1.1 on 2026-09-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_seed_verified_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
