# Generated by Django 6.1.1 on 2026-09-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_hotel_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='star_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
