# Generated by Django 6.1.1 on 2026-09-11 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_description', models.TextField()),
                ('refund_description', models.TextField()),
                ('cancellation_must_be_in_writing', models.BooleanField(default=False)),
                ('refund_processing_days_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('refund_processing_days_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weather_refund_description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'PackageCancellationPolicy',
            },
        ),
        migrations.CreateModel(
            name='YatraPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('package_type', models.CharField(choices=[('CHAR_DHAM', 'Char Dham'), ('DO_DHAM', 'Do Dham')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('duration_nights', models.PositiveSmallIntegerField()),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('departure_location', models.CharField(blank=True, default='', max_length=255)),
                ('route', models.CharField(blank=True, default='', max_length=500)),
                ('operator_name', models.CharField(blank=True, default='', max_length=255)),
                ('season_year', models.PositiveIntegerField(blank=True, null=True)),
                ('hero_image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'YatraPackage',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageCancellationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_days_before', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maximum_days_before', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cancellation_charge_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('refund_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='religious.packagecancellationpolicy')),
            ],
            options={
                'db_table': 'PackageCancellationRule',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageSafetyGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_guidelines', to='religious.yatrapackage')),
            ],
            options={
                'db_table': 'PackageSafetyGuideline',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackagePricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='religious.yatrapackage')),
            ],
            options={
                'db_table': 'PackagePricingRule',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackagePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_label', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('pricing_unit', models.CharField(default='per person', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_custom_price', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='religious.yatrapackage')),
            ],
            options={
                'db_table': 'PackagePricing',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='religious.yatrapackage')),
            ],
            options={
                'db_table': 'PackageInclusion',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_type', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('alternative_text', models.CharField(blank=True, default='', max_length=255)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='religious.yatrapackage')),
            ],
            options={
                'db_table': 'PackageHotel',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to='religious.yatrapackage')),
            ],
            options={
                'db_table': 'PackageGuideline',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='religious.yatrapackage')),
            ],
            options={
                'db_table': 'PackageFeature',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='religious.yatrapackage')),
            ],
            options={
                'db_table': 'PackageExclusion',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='packagecancellationpolicy',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policy', to='religious.yatrapackage'),
        ),
        migrations.CreateModel(
            name='PackageBaggagePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_standard_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('overweight_charge_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('luggage_limit_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_declaration_required', models.BooleanField(default=False)),
                ('weight_verification_required', models.BooleanField(default=False)),
                ('soft_bags_only', models.BooleanField(default=False)),
                ('excess_baggage_storage_available', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baggage_policy', to='religious.yatrapackage')),
            ],
            options={
                'db_table': 'PackageBaggagePolicy',
            },
        ),
        migrations.CreateModel(
            name='PackageItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('route', models.CharField(blank=True, default='', max_length=500)),
                ('overview', models.TextField()),
                ('activities', models.JSONField(blank=True, default=list)),
                ('accommodation', models.CharField(blank=True, default='', max_length=255)),
                ('meal_information', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='religious.yatrapackage')),
            ],
            options={
                'db_table': 'PackageItineraryDay',
                'ordering': ['day_number'],
                'constraints': [models.UniqueConstraint(fields=('package', 'day_number'), name='unique_package_itinerary_day')],
            },
        ),
        migrations.CreateModel(
            name='PackageBookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_steps', to='religious.yatrapackage')),
            ],
            options={
                'db_table': 'PackageBookingStep',
                'ordering': ['step_number'],
                'constraints': [models.UniqueConstraint(fields=('package', 'step_number'), name='unique_package_booking_step')],
            },
        ),
    ]
