# Generated by Django 6.1.1 on 2026-09-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('religious', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yatrapackage',
            name='slug',
            field=models.SlugField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
