# Generated by Django 6.1.1 on 2026-09-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('religious', '0002_yatrapackage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yatrapackage',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
