# Generated by Django 6.1.1 on 2026-09-12 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('religious', '0003_alter_yatrapackage_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('HERO', 'Hero'), ('EXPERIENCE', 'Experience'), ('ITINERARY', 'Itinerary'), ('DESTINATION', 'Destination'), ('HOTEL', 'Hotel'), ('GALLERY', 'Gallery')], default='GALLERY', max_length=30)),
                ('image_url', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('caption', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='religious.yatrapackage')),
            ],
            options={
                'db_table': 'PackageImage',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['package', 'image_type', 'is_active'], name='PackageImag_package_0b41ef_idx')],
            },
        ),
    ]
